---

- name: run nextcloud cron
  become: true
  become_user: '{{ nextcloud_user }}'
  command: 'php -f {{ nextcloud_htdocs }}/cron.php'
  when: (mysql_replication_role is undefined or mysql_replication_role == 'master') and (sync_master is undefined)
